
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/board?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123123

mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml


jwt:
  token-validity-in-second: 300
  refresh-validity-day: 3
  key: com-momoon-jwt-token-access-token-key
  refresh-key: com-momoon-jwt-token-refresh-token-key